config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :contentful
  root to: 'contentful#index'
end

app/models/recipe.rb
# frozen_string_literal: true

class Recipe
  @@recipes = []

  attr_accessor :id, :title, :image_url, :description, :tags, :chef

  mattr_accessor :recipes

  def initialize(_id, _title, _image_url, _description, _tags, _chef)
    @id = _id
    @title = _title
    @image_url = _image_url
    @description = _description
    @tags = _tags
    @chef = _chef
  end

  def self.fetch_recipes
    @client ||= Contentful::Client.new(
      access_token: ENV['CONTENTFUL_ACCESS_TOKEN'],
      space: ENV['CONTENTFUL_SPACE_ID'],
      environment: ENV['Environment_ID'],
      dynamic_entries: :auto,
      raise_errors: true
    )
  end

  def self.all
    @@recipes = []
    recipes = fetch_recipes.entries('sys.contentType.sys.id[match]' => 'recipe', include: 2)
    recipes.each do |r|
      tags = r.fields[:tags] ? r.fields[:tags].collect(&:name).join(',') : ''
      chef = r.fields[:chef] ? r.fields[:chef].name : ''
      @@recipes << Recipe.new(
        r.sys[:id],
        r.fields[:title],
        r.fields[:photo].url(width: 800, height: 800, format: 'jpg', quality: 100),
        r.fields[:description],
        tags,
        chef
      )
    end
    @@recipes
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contentful_controller.rb
# frozen_string_literal: true

class ContentfulController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipes = Recipe.recipes.blank? ? Recipe.all : Recipe.recipes
    @recipe = @recipes.select { |r|  r.id == params[:id] }[0]
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/contentful_helper.rb
module ContentfulHelper
end

app/views/contentful/index.html.erb
<% @recipes.each do |recipe| %>
<div class="row" style="margin-bottom:50px">
    <div class="col-sm-2 float-left"></div>
    <div class="col-sm-8 float-left">
        <h4>Recipe: <%= link_to recipe.title, contentful_path(recipe.id)%></h4>
        <%= image_tag(recipe.image_url, :class => "rounded float-left") %>
    </div>
</div>

<% end %>

app/views/contentful/show.html.erb
<div class="row" style="margin-bottom:50px">
    <div class="col-sm-2 float-left"></div>
    <div class="col-sm-8 float-left">
        <h4>Recipe: <%= @recipe.title %></h4>
        <%= image_tag(@recipe.image_url, :class => "rounded float-left") %>
        <p style="margin-top:50px">Description: <%= @recipe.description%></p>
        <% if !@recipe.tags.blank?%>
        <p>Tags: <%= @recipe.tags%></p>
        <% end %>
        <% if !@recipe.chef.blank?%>
        <p>Chef:<%= @recipe.chef%></p>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>MarleySpoon</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">Marley Spoon</a>
      </div>
    </div>
  </nav>

  <div class="container-fluid text-center">
    <div class="row content">
      <div class="col-sm-2 sidenav">
      </div>
      <div class="col-sm-8 text-left">
        <%= yield %>
        <hr>
      </div>
      <div class="col-sm-2 sidenav">
      </div>
    </div>
  </div>



</body>

</html>